// export const categories = [
//   "All",
//   "Appetizers",
//   "Soups",
//   "Salads",
//   "Pasta (Veg)",
//   "Pasta (Non-Veg)",
//   "Pizza (Veg)",
//   "Pizza (Non-Veg)",
//   "Main Course",
//   "Desserts",
//   "Beverages",
// ]
export const categories = [
  "All",
  "Keema Pav",
  "Omelette",
  "Bhurji",
  "Milkshakes",
  "Thick Shakes",
  "Cold Coffee",
  "Hot Coffee",
  "Mocktails",
  "Hot Chocolate",
  "Chai",
  "Bun Maska",
  "Nonveg Quick Bites",
  "Veg Quick Bites",
  "French Fries",
  "Nonveg Sandwich",
  "Veg Sandwich",
  "Nonveg Garlic Toast",
  "Veg Garlic Toast",
  "Nonveg Burger",
  "Veg Burger",
  "Veg Maggi",
  "Nonveg Maggi",
  "Nonveg Matka Maggi",
  "Veg Matka Maggi"
]

export const menuItems = [
  {
    id: "1",
    name: "Chicken Keema Pav",
    description: "Toasted bread with garlic, butter and herbs.",
    price: 149,
    category: "Keema Pav",
    image: "/classic-garlic-bread-with-herbs-and-butter.jpg",
  },
  {
    id: "2",
    name: "Chicken Cheese Keema Pav",
    description: "Classic garlic bread topped with melted mozzarella.",
    price: 159,
    category: "Keema Pav",
    image: "/cheese-garlic-bread-with-melted-mozzarella.jpg",
  },
  {
    id: "3",
    name: "Chicken Kali Miri Keema Pav",
    description: "Crisp bread topped with fresh tomatoes, basil, and olive oil.",
    price: 169,
    category: "Keema Pav",
    image: "/tomato-basil-bruschetta-appetizer.jpg",
  },
  {
    id: "4",
    name: "Butter Garlic Keema Pav",
    description: "Crispy fried risotto balls stuffed with cheese and vegetables.",
    price: 169,
    category: "Keema Pav",
    image: "/vegetable-arancini-fried-balls.jpg",
  },
  {
    id: "5",
    name: "Chicken Tikka Keema Pav",
    description: "Golden fried mozzarella sticks served with marinara dip.",
    price: 179,
    category: "Keema Pav",
    image: "/fried-mozzarella-sticks-with-dip.jpg",
  },
  {
    id: "6",
    name: "Classic French Omelette",
    description: "Crispy fried calamari rings served with lemon and tartar sauce.",
    price: 50,
    category: "Omelette",
    image: "/fried-calamari-rings.jpg",
  },
  {
    id: "7",
    name: "Sunny Side Up",
    description: "Juicy chicken wings tossed in a spicy Italian herb sauce.",
    price: 50,
    category: "Omelette",
    image: "/spicy-italian-chicken-wings.jpg",
  },
  {
    id: "8",
    name: "Egg Poach",
    description: "A selection of cured meats, cheeses, olives, and pickled vegetables.",
    price: 50,
    category: "Omelette",
    image: "/antipasto-platter-with-meats-cheese.jpg",
  },
  {
    id: "9",
    name: "Spanish Tomato Cheese Omelette",
    description: "A hearty Italian vegetable soup with pasta and beans.",
    price: 60,
    category: "Omelette",
    image: "/vegetable-minestrone.png",
  },
  {
    id: "10",
    name: "Spicy Indian Masala Omelette",
    description: "A rich and creamy soup made with fresh mushrooms.",
    price: 60,
    category: "Omelette",
    image: "/cream-of-mushroom-soup.jpg",
  },
  {
    id: "11",
    name: "Banjo Omelette",
    description: "Classic tomato soup with fresh basil and cream.",
    price: 70,
    category: "Omelette",
    image: "/tomato-basil-soup-with-cream.jpg",
  },
  {
    id: "12",
    name: "Florentine Omelette",
    description: "Hearty lentil soup with vegetables and spices.",
    price: 80,
    category: "Omelette",
    image: "/lentil-vegetable-soup.png",
  },
  {
    id: "13",
    name: "Mexi-Sexy Omelette",
    description: "Crisp lettuce, croutons, and parmesan cheese in a creamy Caesar dressing.",
    price: 80,
    category: "Omelette",
    image: "/caesar-salad-with-lettuce.jpg",
  },
  {
    id: "14",
    name: "Western Omelette",
    description: "Fresh mozzarella, tomatoes, and basil, drizzled with balsamic glaze.",
    price: 90,
    category: "Omelette",
    image: "/caprese-salad-with-mozzarella-tomato.jpg",
  },
  {
    id: "15",
    name: "Egg Tandoori Cheese Banjo",
    description: "Tomatoes, cucumbers, olives, feta cheese, and red onion.",
    price: 90,
    category: "Omelette",
    image: "/greek-salad-feta.png",
  },
  {
    id: "16",
    name: "Tandoori Fire Omelette",
    description: "Classic Caesar salad topped with grilled chicken strips.",
    price: 100,
    category: "Omelette",
    image: "/chicken-caesar-salad-with-grilled-chicken.jpg",
  },
  {
    id: "17",
    name: "Chicken Egg Omelette",
    description: "Penne pasta in a spicy tomato and garlic sauce.",
    price: 110,
    category: "Omelette",
    image: "/penne-arrabiata-pasta-spicy.jpg",
  },
  {
    id: "18",
    name: "Fusilli in Pesto Cream",
    description: "Fusilli pasta in a creamy basil pesto sauce with vegetables.",
    price: 420,
    category: "Pasta (Veg)",
    image: "/fusilli-pesto-pasta-creamy.jpg",
  },
  {
    id: "19",
    name: "Kheema Pav",
    description: "Spaghetti tossed with olive oil, garlic, chili flakes, and parsley.",
    price: 380,
    category: "Pasta (Veg)",
    image: "/kheema-pav.png",
  },
  {
    id: "20",
    name: "Veg Lasagna",
    description: "Layers of pasta, vegetables, cheese, and tomato sauce, baked to perfection.",
    price: 450,
    category: "Pasta (Veg)",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "21",
    name: "Baked Mac 'n' Cheese",
    description: "Classic macaroni in a rich cheese sauce, baked with a crispy top.",
    price: 400,
    category: "Pasta (Veg)",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "22",
    name: "Spinach & Ricotta Ravioli",
    description: "Homemade ravioli stuffed with spinach and ricotta in a light butter-sage sauce.",
    price: 460,
    category: "Pasta (Veg)",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "23",
    name: "Spaghetti Carbonara",
    description: "Spaghetti with bacon, eggs, and parmesan in a creamy sauce.",
    price: 440,
    category: "Pasta (Non-Veg)",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "24",
    name: "Fettuccine Alfredo with Chicken",
    description: "Creamy Alfredo sauce with tender chicken breast strips.",
    price: 480,
    category: "Pasta (Non-Veg)",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "25",
    name: "Spaghetti Bolognese (Chicken)",
    description: "Spaghetti with a rich and hearty chicken meat sauce.",
    price: 420,
    category: "Pasta (Non-Veg)",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "26",
    name: "Penne Carbonara",
    description: "Penne with bacon, eggs, and parmesan in a classic carbonara sauce.",
    price: 410,
    category: "Pasta (Non-Veg)",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "27",
    name: "Margherita Pizza",
    description: "Fresh mozzarella, tomato, basil, and olive oil on a thin crust.",
    price: 350,
    category: "Pizza (Veg)",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "28",
    name: "Four Cheese Pizza",
    description: "A blend of mozzarella, parmesan, gorgonzola, and ricotta cheese.",
    price: 420,
    category: "Pizza (Veg)",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "29",
    name: "Vegetarian Supreme Pizza",
    description: "Peppers, onions, mushrooms, olives, tomatoes, and cheese.",
    price: 400,
    category: "Pizza (Veg)",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "30",
    name: "Pepperoni Pizza",
    description: "Classic pizza with mozzarella cheese and sliced pepperoni.",
    price: 380,
    category: "Pizza (Non-Veg)",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "31",
    name: "BBQ Chicken Pizza",
    description: "Grilled chicken, BBQ sauce, red onions, and melted cheese.",
    price: 450,
    category: "Pizza (Non-Veg)",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "32",
    name: "Meat Lovers Pizza",
    description: "Pepperoni, sausage, bacon, and ham with mozzarella cheese.",
    price: 480,
    category: "Pizza (Non-Veg)",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "33",
    name: "Butter Chicken",
    description: "Tender chicken pieces in a rich, creamy, tomato-based curry.",
    price: 520,
    category: "Main Course",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "34",
    name: "Tandoori Chicken",
    description: "Marinated chicken grilled in a tandoor with aromatic spices.",
    price: 540,
    category: "Main Course",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "35",
    name: "Paneer Tikka Masala",
    description: "Grilled paneer cheese in a creamy, spiced tomato sauce.",
    price: 480,
    category: "Main Course",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "36",
    name: "Dal Makhani",
    description: "Slow-cooked lentils in a rich cream and tomato-based sauce.",
    price: 380,
    category: "Main Course",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "37",
    name: "Tiramisu",
    description: "Classic Italian dessert with mascarpone, espresso, and cocoa.",
    price: 320,
    category: "Desserts",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "38",
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with a molten chocolate center.",
    price: 280,
    category: "Desserts",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "39",
    name: "Panna Cotta",
    description: "Silky smooth Italian cream custard with berries.",
    price: 300,
    category: "Desserts",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "40",
    name: "Gelato",
    description: "Italian ice cream in various flavors.",
    price: 150,
    category: "Desserts",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "41",
    name: "Iced Tea",
    description: "Refreshing homemade iced tea.",
    price: 120,
    category: "Beverages",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "42",
    name: "Fresh Lemonade",
    description: "Freshly squeezed lemon juice with a hint of mint.",
    price: 140,
    category: "Beverages",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "43",
    name: "Cappuccino",
    description: "Classic Italian coffee with espresso and steamed milk.",
    price: 180,
    category: "Beverages",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "44",
    name: "Espresso",
    description: "Strong and bold Italian espresso shot.",
    price: 100,
    category: "Beverages",
    image: "/placeholder.svg?height=200&width=200",
  },
]
